spring:
  profiles:
    active: development

  datasource:
    url: jdbc:postgresql://localhost/dcdb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

logging:
  level:
    ru: debug